services:
 personal:
    container_name: personal
    image: personal:latest
    ports:
       - "8080:8080"    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-standalone:3306/dockering
    networks:
      - harnina_net   
networks:
  harnina_net:
    external: true    
